services:
  api:
    depends_on:
      - postgres
    build: .
    ports:
      - "8000:8000"
    env_file: ".env"


  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ".env"

volumes:
  postgres_data:
